### ISSUE TITLE
how to install ffmpeg

### ISSUE THREAD

**Issue by Dorkerdotcom** [LucientZ/YouTube-Frame-Ripper#8]
how do i install ffmpeg

**Comment by LucientZ** [comment]
It depends on your operating system, but if you go to https://ffmpeg.org/download.html you can find a bunch of download options. I'd suggest looking up a tutorial on how to properly install it and add it to your PATH variable. 

Here are some good tutorials
Windows: https://phoenixnap.com/kb/ffmpeg-windows
Mac and various Unix systems: https://www.hostinger.com/tutorials/how-to-install-ffmpeg
